spring:

  application:
    name: checkin-signup-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.0.75.2:5432/checkin
    username: checkin
    password: checkin!123
  
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update      

server:
  port: 8280
