spring:

  application:
    name: checkin-signup-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.0.75.2:5432/checkin
    username: checkin
    password: checkin!123
  
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update      
    properties:      
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true # https://github.com/spring-projects/spring-boot/issues/12007

server:
  port: 8280
